### PR TITLE
Thresholds annotation overrides

### PR DESCRIPTION
**Pull request by r0bobo**
This adds the possibility to override critical and warning thresholds with astro annotations.

### CODE REVIEW

**Comment by lucasreed** [comment]
Once we merge your other PR and you rebase this branch, the tests should kick off and we'll review then.

**Comment by r0bobo** [comment]
I realized that we probably don't want to do anything with the thresholds if there are no relevant annotations defined. (I also pushed the dependency update to kick off the tests.)

**Comment by r0bobo** [comment]
Hmm. The failed test works on my machine. Maybe the `[]config.Override` slice order is non-deterministic?

**Review by lucasreed — APPROVED** [review]
Sorry this took so long! I just tested this out locally and seems to work as expected. Thank you!

**Pull request merged**
